system:
  mode: dev
  addr: 4444
  iplimit-count: 15000
  iplimit-time: 3600
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
cors:
  mode: whitelist
  whitelist:
    - allow-origin: example1.com
      allow-methods: GET, POST
      allow-headers: content-type
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
        Content-Type
      allow-credentials: true
jwt:
  signing-key: Qm9uZQ==
  expires-time: 604800
  buffer-time: 86400
  issuer: Bone
local:
  path: uploads/file
  store-path: uploads/file
casbin:
  model-path: './model/rbac_model.conf'

mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: m_competition
  username: root
  password: 1qaz!QAZ
  max-idle-conns: 50
  max-open-conns: 200
  log-mode: error
  log-zap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
zap:
  level: info
  format: console
  prefix: '[MC]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

sign:
  number: 3